### ISSUE TITLE
多goroutinue多level写同一个文件会导致文件内容乱序

### ISSUE THREAD

**Issue by BarmBamos** [YoungPioneers/blog4go#19]
![image](https://user-images.githubusercontent.com/24584948/41589255-a40f1bba-73e6-11e8-8f02-e6434895c933.png)

当多个 level 写同一个文件时，blog 锁并不能保证会安全的写入文件， 会导致msg乱序

**Comment by hjweddie** [comment]
嗯嗯，这个看起来是个逻辑上的bug, 请问多个level写同一个文件的时候，使用的配置是怎么样的呢？

**Comment by BarmBamos** [comment]
<blog4go minlevel="debug">
	<filter levels="info,error" colored="false">
		<file path="output_blog4go.log"></file>
	</filter>
</blog4go>
是这样的配置，我看了代码，发现当info error日志要写到同一个文件中去的时候只产生了一个文件句柄，文件句柄没有加锁会导致这个问题。

**Comment by BarmBamos** [comment]
“
<blog4go minlevel="debug">
	<filter levels="info,error" colored="false">
		<file path="output_blog4go.log"></file>
	</filter>
</blog4go>
”

**Comment by BarmBamos** [comment]
![image](https://user-images.githubusercontent.com/24584948/44329944-5c943080-a498-11e8-89ac-41ea86d24d09.png)

**Comment by hjweddie** [comment]
谢谢反馈，最近在multi writer的写操作加上了锁，能避免这个问题

commit:
https://github.com/YoungPioneers/blog4go/commit/6cabe173eb084d34eac5653a0395f0b21774e748
