### ISSUE TITLE
关于benchmark的两个问题

### ISSUE THREAD

**Issue by JessonChan** [YoungPioneers/blog4go#2]
1、你性能测试用的哪个平台、什么配置？
我在自己的mac上测试出来的结果和你公开的不太一样
![image](https://cloud.githubusercontent.com/assets/707691/13595127/e1fb8ae6-e543-11e5-995e-d25917305459.png)

2、测试多次，发现每次都是在L46输出有问题
![image](https://cloud.githubusercontent.com/assets/707691/13595142/fa2d4528-e543-11e5-8e87-2a272d666f02.png)

**Comment by JessonChan** [comment]
另外，使用timeCache很巧妙，但有精确度并不严格，虽然不一定所有的场景都需要这样严格的时间

**Comment by hjweddie** [comment]
1.我做测试的在 ubuntu 14.04LTS下做的， 4核，500G HDD 7200转的。
2.请问跑的是哪一测试程序呢？ 是使用神噩梦方法运行测试用例的呢？
感谢～

**Comment by JessonChan** [comment]
@hjweddie 
就是直接 
go test -test.bench=".*" -benchmem
这样跑的

**Comment by hjweddie** [comment]
好的，谢谢你的反馈，我去排查下这是什么问题。
对于你在mac做的benchmark我也会仔细看看。

**Comment by hjweddie** [comment]
@JessonChan 第2个问题是日志内容错乱的问题，现在应该修复好了。
https://github.com/YoungPioneers/blog4go/commit/f6c6cbefbea23e6fd8d5fa65ed7056bd5935043b

**Comment by JessonChan** [comment]
是的，刚刚测试没有发现问题。

**Comment by hjweddie** [comment]
@JessonChan 这个问题在于，通过配置文件初始化log实例的时候，或出现多个不同bufio.Writer并发写同一个文件造成的～
我的解决方案是，对于配置文件中，同一项filter中，只生成一个writer，一定程度避免多个writer实例并发写同一个文件

**Comment by JessonChan** [comment]
嗯，有时间我再仔细研究一下你的方案。

**Comment by JessonChan** [comment]
@hjweddie 刚刚想到 timeCache不是线程安全的

**Comment by hjweddie** [comment]
@JessonChan 在我开发的过程中认为timeCache线程安全性不是很重要，log的时间有细微的误差对于我来说关系并不大。不知道你的想法是怎么样的呢？

**Comment by JessonChan** [comment]
误差只是一个方面，这个误差也并不会太大。线程不安全的结果就是有可能在某些读写竞争引发data race 的panic，尤其是go1.6

**Comment by hjweddie** [comment]
是的，我们刚升级到go1.6的时候也意识到了这个问题，但是现在我们公司内高qps的程序使用这个log的几个月了，过程中并没有出现 竞态 panic的问题

**Comment by hjweddie** [comment]
@JessonChan 在今日的更新里面，针对go1.6的race data添加了相关的锁机制来保障不发生竞争，包括timeCache
