### ISSUE TITLE
timeCache.go 内会导致cpu占用略高啊

### ISSUE THREAD

**Issue by andylau004** [YoungPioneers/blog4go#23]
timeCache.go文件内

		t := time.Tick(1 * time.Millisecond)

这行代码,每一毫秒执行一次,程序空转,就导致cpu占用至少20+%
..是不是有问题.此处逻辑

**Comment by hjweddie** [comment]
确实会占用挺多cpu的，准备把时间间隔改回1秒钟

commit:
https://github.com/YoungPioneers/blog4go/commit/8821c0432838df80af037180d50eb8af00e59ab6

**Comment by andylau004** [comment]
> 确实会占用挺多cpu的，准备把时间间隔改回1秒钟
> 
> commit:
> [8821c04](https://github.com/YoungPioneers/blog4go/commit/8821c0432838df80af037180d50eb8af00e59ab6)

呃，，如果改回１秒，，会不会导致，日志写入文件，会慢的问题？

**Comment by hjweddie** [comment]
> > 确实会占用挺多cpu的，准备把时间间隔改回1秒钟
> > commit:
> > [8821c04](https://github.com/YoungPioneers/blog4go/commit/8821c0432838df80af037180d50eb8af00e59ab6)
> 
> 呃，，如果改回１秒，，会不会导致，日志写入文件，会慢的问题？

为什么会有这种疑问呢？ 程序逻辑上timecache更新的频率跟日志flush的频率并没关系
