### ISSUE TITLE
希望配置文件可以支持配置Console输出

### ISSUE THREAD

**Issue by divisoryang** [YoungPioneers/blog4go#7]
在平时测试的时候挺需要的，调试时用Console，线上用File。

都可以在配置文件里设置会方便很多。

**Comment by jjjachyty** [comment]
同楼上 一般开发的时候 都是控制台和文件都要 上线后 只要文件

**Comment by hjweddie** [comment]
@divisoryang @jjjachyty 对console的支持已经提交到master分支了～
谢谢大家的建议

**Comment by hjweddie** [comment]
[commits](https://github.com/YoungPioneers/blog4go/commit/8a99c170e448ee20f5db783faaf42fdaab476b72)
